tap "homebrew/cask"
brew "neovim"
brew "exa"
brew "kubectl"
brew "asdf"
brew "tmux"
brew "libyaml"
brew "reattach-to-user-namespace"
brew "universal-ctags"
brew "ag"
brew "int128/kubelogin/kubelogin"
tap "koekeishiya/formulae"
brew "koekeishiya/formulae/yabai", restart_service: true
brew "koekeishiya/formulae/skhd", restart_service: true
brew "libpq"
brew "k9s"
